# version: '3.9'


services:
  order-service:
    build:
      context: ./order-service
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orderdb
    ports:
      - "5432:5432"  # <--- FIXED
